### ISSUE TITLE
Got an Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric, : invalid 'x' 

### ISSUE THREAD

**Issue by yeyup** [Wubeizhongxinghua/easy-to-use-seqff#1]
In brief, when I ran your Rscript, I got the error :
![image](https://github.com/Wubeizhongxinghua/easy-to-use-seqff/assets/101948567/7e9d569c-884c-4614-956b-0619cf9ab73e)
Could you let me know why I have such an error? Or how to solve it?

**Comment by Wubeizhongxinghua** [comment]
Is it convenient for you to give me your bam file? Everything works fine in my environment with R version 4.2.1 and Rsamtools version 2.14.0.

**Comment by Wubeizhongxinghua** [comment]
Is it convenient for you to give me your bam file? Everything works fine in my environment with R 4.2.1 and Rsamtools 2.14.0.

**Comment by yeyup** [comment]
> Is it convenient for you to give me your bam file? Everything works fine in my environment with R 4.2.1 and Rsamtools 2.14.0.

Sorry for the late response, I have confirmed that when using the different reference genomes hg19, the generated chromosome representation lacks 'chr'. If possible, could you add a small feature to automatically determine if the chromosome representation in the input bam carries 'chr' or not
