### ISSUE TITLE
Does the input BAM file need to be aligned specifically to the hg19?

### ISSUE THREAD

**Issue by TongZhou202103** [Wubeizhongxinghua/easy-to-use-seqff#2]
Thanks for sharing! 
I have a basic question: does the input BAM file need to be aligned specifically to the hg19?

**Comment by Wubeizhongxinghua** [comment]
Thanks for your issue.

Unfortunately, the original paper did the analysis based on hg19 genome, hence it is recommended to use seqff for hg19-based bam. 

I shall use liftover to make a new seqff available for hg38 later in my spare time.
